//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalBruResturant.ResturantService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/FinalBruResturantWCFService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RewardPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RewardPoints {
            get {
                return this.RewardPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.RewardPointsField, value) != true)) {
                    this.RewardPointsField = value;
                    this.RaisePropertyChanged("RewardPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/FinalBruResturantWCFService")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumPeopleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumPeople {
            get {
                return this.NumPeopleField;
            }
            set {
                if ((this.NumPeopleField.Equals(value) != true)) {
                    this.NumPeopleField = value;
                    this.RaisePropertyChanged("NumPeople");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((this.ReservationIdField.Equals(value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResturantService.IResturantService")]
    public interface IResturantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/findAllUsers", ReplyAction="http://tempuri.org/IResturantService/findAllUsersResponse")]
        FinalBruResturant.ResturantService.User[] findAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/findAllUsers", ReplyAction="http://tempuri.org/IResturantService/findAllUsersResponse")]
        System.Threading.Tasks.Task<FinalBruResturant.ResturantService.User[]> findAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/findAllReservations", ReplyAction="http://tempuri.org/IResturantService/findAllReservationsResponse")]
        FinalBruResturant.ResturantService.Reservation[] findAllReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/findAllReservations", ReplyAction="http://tempuri.org/IResturantService/findAllReservationsResponse")]
        System.Threading.Tasks.Task<FinalBruResturant.ResturantService.Reservation[]> findAllReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/findUserByUsername", ReplyAction="http://tempuri.org/IResturantService/findUserByUsernameResponse")]
        FinalBruResturant.ResturantService.User findUserByUsername(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/findUserByUsername", ReplyAction="http://tempuri.org/IResturantService/findUserByUsernameResponse")]
        System.Threading.Tasks.Task<FinalBruResturant.ResturantService.User> findUserByUsernameAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/InsertIntoDB", ReplyAction="http://tempuri.org/IResturantService/InsertIntoDBResponse")]
        void InsertIntoDB(FinalBruResturant.ResturantService.Reservation reservation, FinalBruResturant.ResturantService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/InsertIntoDB", ReplyAction="http://tempuri.org/IResturantService/InsertIntoDBResponse")]
        System.Threading.Tasks.Task InsertIntoDBAsync(FinalBruResturant.ResturantService.Reservation reservation, FinalBruResturant.ResturantService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/InsertReservationIntoDB", ReplyAction="http://tempuri.org/IResturantService/InsertReservationIntoDBResponse")]
        void InsertReservationIntoDB(FinalBruResturant.ResturantService.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/InsertReservationIntoDB", ReplyAction="http://tempuri.org/IResturantService/InsertReservationIntoDBResponse")]
        System.Threading.Tasks.Task InsertReservationIntoDBAsync(FinalBruResturant.ResturantService.Reservation reservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/InsertUserIntoDB", ReplyAction="http://tempuri.org/IResturantService/InsertUserIntoDBResponse")]
        void InsertUserIntoDB(FinalBruResturant.ResturantService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResturantService/InsertUserIntoDB", ReplyAction="http://tempuri.org/IResturantService/InsertUserIntoDBResponse")]
        System.Threading.Tasks.Task InsertUserIntoDBAsync(FinalBruResturant.ResturantService.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResturantServiceChannel : FinalBruResturant.ResturantService.IResturantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResturantServiceClient : System.ServiceModel.ClientBase<FinalBruResturant.ResturantService.IResturantService>, FinalBruResturant.ResturantService.IResturantService {
        
        public ResturantServiceClient() {
        }
        
        public ResturantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResturantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResturantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResturantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FinalBruResturant.ResturantService.User[] findAllUsers() {
            return base.Channel.findAllUsers();
        }
        
        public System.Threading.Tasks.Task<FinalBruResturant.ResturantService.User[]> findAllUsersAsync() {
            return base.Channel.findAllUsersAsync();
        }
        
        public FinalBruResturant.ResturantService.Reservation[] findAllReservations() {
            return base.Channel.findAllReservations();
        }
        
        public System.Threading.Tasks.Task<FinalBruResturant.ResturantService.Reservation[]> findAllReservationsAsync() {
            return base.Channel.findAllReservationsAsync();
        }
        
        public FinalBruResturant.ResturantService.User findUserByUsername(string username, string password) {
            return base.Channel.findUserByUsername(username, password);
        }
        
        public System.Threading.Tasks.Task<FinalBruResturant.ResturantService.User> findUserByUsernameAsync(string username, string password) {
            return base.Channel.findUserByUsernameAsync(username, password);
        }
        
        public void InsertIntoDB(FinalBruResturant.ResturantService.Reservation reservation, FinalBruResturant.ResturantService.User user) {
            base.Channel.InsertIntoDB(reservation, user);
        }
        
        public System.Threading.Tasks.Task InsertIntoDBAsync(FinalBruResturant.ResturantService.Reservation reservation, FinalBruResturant.ResturantService.User user) {
            return base.Channel.InsertIntoDBAsync(reservation, user);
        }
        
        public void InsertReservationIntoDB(FinalBruResturant.ResturantService.Reservation reservation) {
            base.Channel.InsertReservationIntoDB(reservation);
        }
        
        public System.Threading.Tasks.Task InsertReservationIntoDBAsync(FinalBruResturant.ResturantService.Reservation reservation) {
            return base.Channel.InsertReservationIntoDBAsync(reservation);
        }
        
        public void InsertUserIntoDB(FinalBruResturant.ResturantService.User user) {
            base.Channel.InsertUserIntoDB(user);
        }
        
        public System.Threading.Tasks.Task InsertUserIntoDBAsync(FinalBruResturant.ResturantService.User user) {
            return base.Channel.InsertUserIntoDBAsync(user);
        }
    }
}
